### ISSUE TITLE
Comment-only updates are ignored

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/firefox-l10n-source#73]
Change in mozilla-central: https://hg.mozilla.org/mozilla-central/rev/c56067a4f8baa95b4f0387a53958214acd1dfeef
gecko-dev: https://github.com/mozilla/gecko-dev/commit/b8f5675c3da77fdecf835c10df13a5542bcfc9b7

Looks like it never made it to the repo: https://github.com/mozilla-l10n/firefox-l10n-source/blob/main/devtools/shared/debugger-paused-reasons.ftl

**Comment by eemeli** [comment]
It looks like the earlier fix of mozilla/moz-l10n#17 should be expanded to care about all parts of an entry, not just the pattern value.
